// index.js

/**
 * Required External Modules
 */

/**
 * App Variables
 */

const path = require("path");
var express = require('express'),
  app = express(),
  port = process.env.PORT || 8080;
const session = require('express-session');
var bodyParser = require('body-parser');
var fs = require('fs');

var swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  swaggerDefinition: {
    info: {
      title: 'Connected Logistics API',
      version: '1.0.0',
      description: 'DGFF Connected Logistics autogenerated Swagger API documentation. <br> <br>' +
        'Note! <br> __By creating a company account you agree the data and actions that you ' +
        ' submit and perform in this sandbox are entirely at your own responsibility. We recommend that you do not introduce private, commercial or other sensitive information in this sandbox since its exposure cannot be guaranteed. IATA is not liable for your actions or data.__' +
        '<br> <br> ' +
        'Steps to follow in order to test the APIs: <br>' +
        ' 1. Create a company via ```POST /companies```. You will need __companyId__ and __companyPin__ at a later stage, so keep them safely/memorize them. Only users that know the **companyPin** number can create an account under your company registration.<br>' +
        ' 2. Create a user for your __companyId__ via ```POST /companies/yourCompanyId/users```. <br>' +
        ' 3. Login a user via ```POST /companies/yourCompanyId/users/login```. Will get a token (JWT) in the login response which is valid for 72 hours. <br>' +
        ' 4. Add the token in the **Authorize** box. The following syntax must be used: ```Bearer yourtoken```. The endpoints with **lock** icon can be accessed only after the token is added to the **Authorize** box, which automatically ' +
        'adds it to the **Authorization** header. <br>' +
        ' 5. Add logistics objects to the server via ```POST /companies/yourCompanyId/los```. You can find some examples of logistics objects in [Github](https://github.com/IATA-Cargo/Sandbox). ' + 
        ' Logistics object must contain ```@type``` field: Airwaybill, Housemanifest, Housewaybill or Booking.<br>' +
        ' 6. Some of the endpoints (example: ```GET /companies```) can only be accessed with the ```serverSecret``` configured in the server ```config.js``` file. <br>' + 
        '<br> **Publish - subscribe model** <br>' +
        ' 1. Follow the instructions above in order to create a company, users and login. <br>' + 
        ' 2. Subscription information of this server can be retrieved via ```GET /serverInformation?topic=logisticsObjectType```. <br>' +
        ' 3. The endpoint ```POST /callbackUrl``` is used to receive logistics objects from the publishers to which the current server is subscribed to. ' +
        'You can configure the **subscriptionSecret** as instructed in [Github Sandbox repository](https://github.com/IATA-Cargo/Sandbox). The publishers that have the subscription secret can send ' +
        ' logistics objects to this endpoint.<br>' +
        '<br> More information about ONE Record specification on [IATA Github repository](https://github.com/IATA-Cargo/ONE-Record). <br>'
    },
    securityDefinitions: {
      bearerAuth: {
        type: 'apiKey',
        name: 'Authorization',
        in: 'header',
        scheme: 'bearer',
        description: 'For accessing the API a valid JWT token must be passed in all the queries in the **Authorization** header. <br>' +
          'A valid JWT token is generated by the API and retourned as answer of a call to the route ```POST /companies/yourCompanyId/users/login``` ' +
          ' giving a valid username & password. The returned token is valid for 72 hours. <br>' +
          'The following syntax must be used in the **Authorization** header: ```Bearer yourtoken```.'
      }
    },
  },
  apis: ['./api/routes/*.js'],
};

const specs = swaggerJsdoc(options);


// Set Swagger API documentation
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
app.get('/api-docs.json', (req, res) => {  
  res.setHeader('Content-Type', 'application/json');  
  res.status(200).json(specs);  
}); 
/**
 *  App Configuration
 */
var hwbRouter = require('/routes/housewaybill');
/**
 * Routes Definitions
 */
app.use('/housewaybill', hwbRouter);
app.get("/loginlanding",(req,res) => {
    res.render("login", { title: "Login" });
  });

app.get("/", (req, res) => {
    res.render("index", { title: "Home" });
  });


app.use(bodyParser.urlencoded({ extended: true }));
app.post('/login', (req, res) => {
    var data = req.body;
    console.log(req.body.email);
    if (req.body.email=='')
    {
      res.append('Content-Type', 'application/json');
      res.send('please provide username and password');
    }
    else
    {
    console.log(req.body.email);
    app.use(session({
        key : req.body.email,
        secret : req.body.password,
        resave : true,
        saveUninitialized : true,
        cookie : {
            expires : 60000,
            httpOnly : true,
            path : '/login',
            secure : "auto",
            sameSite : true
        }
    }));
    var output = JSON.stringify(data);
    //res.append('Content-Type', 'application/json');
     res.render('afterlogin', { title: 'Welcome ' + req.body.email, email: req.body.email });
    // res.redirect('/afterlogin?email=' + req.body.email);
    // res.end(output);
  }
  });

/**
 * Server Activation
 */


app.listen(port);
console.log('Application is started at port : ' + port);

app.set("views", path.join(__dirname, "views"));
app.set("view engine", "pug");
app.use(express.static(path.join(__dirname,"public")));



